
# *********************************************
# ************ -*- 数据库连接配置 -*- ************
# *********************************************

database_host:
  - data_base:
      name: happy_seven
      host: rr-2zeh202up6hhmg5kc.mysql.rds.aliyuncs.com

  - data_base:
      name: shard
      host: rr-2zeosaq969q3d1lw2.mysql.rds.aliyuncs.com
      size:
        start: 0
        end: 127

  - data_base:
      name: shard
      host: rr-2zeo525og61jh6wz4.mysql.rds.aliyuncs.com
      size:
        start: 128
        end: 255

  - data_base:
      name: shard
      host: rr-2ze9l7as602nysv4y.mysql.rds.aliyuncs.com
      size:
        start: 256
        end: 383

  - data_base:
      name: shard
      host: rr-2ze963rfwrs7nq264.mysql.rds.aliyuncs.com
      size:
        start: 384
        end: 511


datamarket:
  host: 172.16.0.248
  user: root
  pw: Qiyue@123
  db_name: happy_seven
